### ISSUE TITLE
LOADED PRETRAINED MODEL AND THEN...

### ISSUE THREAD

**Issue by MeiCadel** [m2man/HADA#1]
My running process keeps stucking loading the pretrained model. What might be the possible reasons for this problem？
<img width="461" alt="image" src="https://github.com/m2man/HADA/assets/33341798/653d4b61-86c5-4438-a565-8f099cf5d609">

**Comment by m2man** [comment]
Hi there, thank you for your interest in our research. Regarding your issue, it is not about loading the pretrained model. Since it printed "LOADED PRETRAINED ..." on the screen meaning that the model has successfully loaded, the issue may be the later step which can be loading batch in order to train/evaluate or start running on each batch. For further investigation, you can add the print command right after the loaded model command.

**Comment by MeiCadel** [comment]
that's very helpful. thanks a lot. my problem is solved.

**Comment by MeiCadel** [comment]
> Hi there, thank you for your interest in our research. Regarding your issue, it is not about loading the pretrained model. Since it printed "LOADED PRETRAINED ..." on the screen meaning that the model has successfully loaded, the issue may be the later step which can be loading batch in order to train/evaluate or start running on each batch. For further investigation, you can add the print command right after the loaded model command.



> Hi there, thank you for your interest in our research. Regarding your issue, it is not about loading the pretrained model. Since it printed "LOADED PRETRAINED ..." on the screen meaning that the model has successfully loaded, the issue may be the later step which can be loading batch in order to train/evaluate or start running on each batch. For further investigation, you can add the print command right after the loaded model command.

that's very helpful. thanks a lot. my problem is solved.

**Comment by MeiCadel** [comment]
> Hi there, thank you for your interest in our research. Regarding your issue, it is not about loading the pretrained model. Since it printed "LOADED PRETRAINED ..." on the screen meaning that the model has successfully loaded, the issue may be the later step which can be loading batch in order to train/evaluate or start running on each batch. For further investigation, you can add the print command right after the loaded model command.

that's very helpful. thanks a lot. my problem is solved.
